import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'en' | 'hi' | 'ta' | 'te' | 'bn' | 'mr' | 'gu' | 'kn';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation dictionary
const translations: Record<Language, Record<string, string>> = {
  en: {
    appName: 'Sarthi',
    tagline: 'Your AI Guide for Every Step of Life',
    selectLanguage: 'Select Your Language',
    continue: 'Continue',
    login: 'Login',
    signup: 'Sign Up',
    logout: 'Logout',
    dashboard: 'Dashboard',
    profile: 'Profile',
    welcome: 'Welcome',
    studentSupport: 'Student Support',
    govSchemes: 'Government Schemes',
    careerGuidance: 'Career Guidance',
    aiAssistant: 'AI Assistant',
    chat: 'Chat with AI',
    email: 'Email',
    password: 'Password',
    name: 'Full Name',
    dontHaveAccount: "Don't have an account?",
    alreadyHaveAccount: 'Already have an account?',
    getStarted: 'Get Started',
    features: 'Features',
    aboutUs: 'About Us',
    howItWorks: 'How It Works',
    multilingualSupport: 'Multilingual Support',
    lowBandwidth: 'Low Bandwidth Friendly',
    freeForAll: 'Free for All Indians',
    studyPlanner: 'AI Study Planner',
    doubtSolving: 'Doubt Solving',
    mentalWellness: 'Mental Wellness',
    schemeChecker: 'Scheme Eligibility Checker',
    skillRecommendation: 'Skill Recommendations',
    resumeTips: 'Resume Building Tips',
    jobAwareness: 'Job & Internship Awareness',
    askQuestion: 'Ask your question...',
    send: 'Send',
    voiceInput: 'Voice Input',
    loading: 'Loading...',
    viewDetails: 'View Details',
    checkEligibility: 'Check Eligibility',
    apply: 'Apply',
    progressTracking: 'Progress Tracking',
    chatHistory: 'Chat History',
    settings: 'Settings',
    newChat: 'New Chat',
    searchChats: 'Search chats...',
    navigate: 'Navigate',
    pinned: '📌 Pinned',
    today: 'Today',
    yesterday: 'Yesterday',
    older: 'Older',
    folders: 'Folders',
    noConversations: 'No conversations yet',
    notifications: 'Citizen Notifications & Official Alerts',
    citizenDashboard: 'Citizen Dashboard',
    recentActivity: 'Recent Activity',
    studyPlanStatus: 'Study Plan Status',
    exploreServices: 'Explore Services',
    savedSchemes: 'Saved Schemes',
    totalActivities: 'Total Activities',
    userCategory: 'User Category',
  },
  hi: {
    appName: 'Sarthi',
    tagline: 'जीवन के हर कदम पर आपका AI मार्गदर्शक',
    selectLanguage: 'अपनी भाषा चुनें',
    continue: 'जारी रखें',
    login: 'लॉगिन',
    signup: 'साइन अप करें',
    logout: 'लॉगआउट',
    dashboard: 'डैशबोर्ड',
    profile: 'प्रोफाइल',
    welcome: 'स्वागत है',
    studentSupport: 'छात्र सहायता',
    govSchemes: 'सरकारी योजनाएं',
    careerGuidance: 'करियर मार्गदर्शन',
    aiAssistant: 'AI सहायक',
    chat: 'AI से बात करें',
    email: 'ईमेल',
    password: 'पासवर्ड',
    name: 'पूरा नाम',
    dontHaveAccount: 'खाता नहीं है?',
    alreadyHaveAccount: 'पहले से खाता है?',
    getStarted: 'शुरू करें',
    features: 'विशेषताएं',
    aboutUs: 'हमारे बारे में',
    howItWorks: 'यह कैसे काम करता है',
    multilingualSupport: 'बहुभाषी समर्थन',
    lowBandwidth: 'कम बैंडविड्थ के अनुकूल',
    freeForAll: 'सभी भारतीयों के लिए मुफ्त',
    studyPlanner: 'AI अध्ययन योजनाकार',
    doubtSolving: 'संदेह समाधान',
    mentalWellness: 'मानसिक स्वास्थ्य',
    schemeChecker: 'योजना पात्रता जांचकर्ता',
    skillRecommendation: 'कौशल सिफारिशें',
    resumeTips: 'रिज्यूमे बनाने के टिप्स',
    jobAwareness: 'नौकरी और इंटर्नशिप जागरूकता',
    askQuestion: 'अपना सवाल पूछें...',
    send: 'भेजें',
    voiceInput: 'वॉयस इनपुट',
    loading: 'लोड हो रहा है...',
    viewDetails: 'विवरण देखें',
    checkEligibility: 'पात्रता जांचें',
    apply: 'आवेदन करें',
    progressTracking: 'प्रगति ट्रैकिंग',
    chatHistory: 'चैट इतिहास',
    settings: 'सेटिंग्स',
    newChat: 'नयी चैट',
    searchChats: 'चैट खोजें...',
    navigate: 'नेविगेट करें',
    pinned: '📌 पिन किए गए',
    today: 'आज',
    yesterday: 'कल',
    older: 'पुराने',
    folders: 'फ़ोल्डर',
    noConversations: 'अभी कोई बातचीत नहीं',
    citizenDashboard: 'नागरिक डैशबोर्ड',
    recentActivity: 'हाल की गतिविधि',
    studyPlanStatus: 'अध्ययन योजना स्थिति',
    exploreServices: 'सेवाएं खोजें',
    savedSchemes: 'सहेजी गई योजनाएं',
    totalActivities: 'कुल गतिविधियां',
    userCategory: 'उपयोगकर्ता श्रेणी',
  },
  ta: {
    appName: 'Sarthi',
    tagline: 'உங்கள் வாழ்வின் ஒவ்வொரு படியிலும் AI வழிகாட்டி',
    selectLanguage: 'உங்கள் மொழியைத் தேர்ந்தெடுக்கவும்',
    continue: 'தொடரவும்',
    login: 'உள்நுழைய',
    signup: 'பதிவு செய்க',
    logout: 'வெளியேறு',
    dashboard: 'கட்டுப்பாட்டு பலகை',
    profile: 'சுயவிவரம்',
    welcome: 'வரவேற்கிறோம்',
    studentSupport: 'மாணவர் ஆதரவு',
    govSchemes: 'அரசு திட்டங்கள்',
    careerGuidance: 'தொழில் வழிகாட்டுதல்',
    aiAssistant: 'AI உதவியாளர்',
    chat: 'AI உடன் அரட்டை',
    email: 'மின்னஞ்சல்',
    password: 'கடவுச்சொல்',
    name: 'முழு பெயர்',
    dontHaveAccount: 'கணக்கு இல்லையா?',
    alreadyHaveAccount: 'ஏற்கனவே கணக்கு உள்ளதா?',
    getStarted: 'தொடங்குங்கள்',
    features: 'அம்சங்கள்',
    aboutUs: 'எங்களை பற்றி',
    howItWorks: 'இது எப்படி வேலை செய்கிறது',
    multilingualSupport: 'பன்மொழி ஆதரவு',
    lowBandwidth: 'குறைந்த பேண்ட்விட்த்',
    freeForAll: 'அனைத்து இந்தியர்களுக்கும் இலவசம்',
    studyPlanner: 'AI படிப்பு திட்டமிடுபவர்',
    doubtSolving: 'சந்தேக தீர்வு',
    mentalWellness: 'மன நல்வாழ்வு',
    schemeChecker: 'திட்ட தகுதி சரிபார்ப்பு',
    skillRecommendation: 'திறன் பரிந்துரைகள்',
    resumeTips: 'பயிற்சி குறிப்புகள்',
    jobAwareness: 'வேலை விழிப்புணர்வு',
    askQuestion: 'உங்கள் கேள்வியைக் கேளுங்கள்...',
    send: 'அனுப்பு',
    voiceInput: 'குரல் உள்ளீடு',
    loading: 'ஏற்றுகிறது...',
    viewDetails: 'விவரங்களைக் காண்க',
    checkEligibility: 'தகுதியைச் சரிபார்க்கவும்',
    apply: 'விண்ணப்பிக்கவும்',
    progressTracking: 'முன்னேற்ற கண்காணிப்பு',
    chatHistory: 'அரட்டை வரலாறு',
    settings: 'அமைப்புகள்',
    newChat: 'புதிய அரட்டை',
    searchChats: 'அரட்டைகளைத் தேடு...',
    navigate: 'வழிசெலுத்து',
    pinned: '📌 பின் செய்யப்பட்டது',
    today: 'இன்று',
    yesterday: 'நேற்று',
    older: 'பழையவை',
    folders: 'கோப்புறைகள்',
    noConversations: 'இதுவரை எந்த அரட்டையும் இல்லை',
    citizenDashboard: 'குடிமக்கள் கட்டுப்பாட்டு பலகை',
    recentActivity: 'சமீபத்திய செயல்பாடு',
    studyPlanStatus: 'படிப்பு திட்ட நிலை',
    exploreServices: 'சேவைகளை ஆராயுங்கள்',
    savedSchemes: 'சேமிக்கப்பட்ட திட்டங்கள்',
    totalActivities: 'மொத்த செயல்பாடுகள்',
    userCategory: 'பயனர் வகை',
  },
  te: {
    appName: 'Sarthi',
    tagline: 'జీవితంలో ప్రతి అడుగులో మీ AI మార్గదర్శి',
    selectLanguage: 'మీ భాషను ఎంచుకోండి',
    continue: 'కొనసాగించు',
    login: 'లాగిన్',
    signup: 'సైన్ అప్',
    logout: 'లాగ్అవుట్',
    dashboard: 'డాష్‌బోర్డ్',
    profile: 'ప్రొఫైల్',
    welcome: 'స్వాగతం',
    studentSupport: 'విద్యార్థి మద్దతు',
    govSchemes: 'ప్రభుత్వ పథకాలు',
    careerGuidance: 'కెరీర్ మార్గదర్శకత్వం',
    aiAssistant: 'AI సహాయకుడు',
    chat: 'AI తో చాట్',
    email: 'ఇమెయిల్',
    password: 'పాస్‌వర్డ్',
    name: 'పూర్తి పేరు',
    dontHaveAccount: 'ఖాతా లేదా?',
    alreadyHaveAccount: 'ఇప్పటికే ఖాతా ఉందా?',
    getStarted: 'ప్రారంభించండి',
    features: 'లక్షణాలు',
    aboutUs: 'మా గురించి',
    howItWorks: 'ఇది ఎలా పనిచేస్తుంది',
    multilingualSupport: 'బహుభాషా మద్దతు',
    lowBandwidth: 'తక్కువ బ్యాండ్‌విడ్త్',
    freeForAll: 'అందరు భారతీయులకు ఉచితం',
    studyPlanner: 'AI అధ్యయన ప్లానర్',
    doubtSolving: 'సందేహ పరిష్కారం',
    mentalWellness: 'మానసిక ఆరోగ్యం',
    schemeChecker: 'పథక అర్హత తనిఖీ',
    skillRecommendation: 'నైపుణ్య సిఫార్సులు',
    resumeTips: 'రెజ్యూమ్ చిట్కాలు',
    jobAwareness: 'ఉద్యోగ అవగాహన',
    askQuestion: 'మీ ప్రశ్న అడగండి...',
    send: 'పంపండి',
    voiceInput: 'వాయిస్ ఇన్‌పుట్',
    loading: 'లోడ్ అవుతోంది...',
    viewDetails: 'వివరాలు చూడండి',
    checkEligibility: 'అర్హతను తనిఖీ చేయండి',
    apply: 'దరఖాస్తు చేయండి',
    progressTracking: 'పురోగతి ట్రాకింగ్',
    chatHistory: 'చాట్ చరిత్ర',
    settings: 'సెట్టింగ్‌లు',
    newChat: 'కొత్త చాట్',
    searchChats: 'చాట్‌లను వెతకండి...',
    navigate: 'నావిగేట్ చేయండి',
    pinned: '📌 పిన్ చేయబడింది',
    today: 'ఈరోజు',
    yesterday: 'నిన్న',
    older: 'పాతవి',
    folders: 'ఫోల్డర్లు',
    noConversations: 'ఇంకా ఎలాంటి చాట్‌లు లేవు',
    citizenDashboard: 'పౌరుల డాష్‌బోర్డ్',
    recentActivity: 'ఇటీవలి కార్యాచరణ',
    studyPlanStatus: 'స్టడీ ప్లాన్ స్థితి',
    exploreServices: 'సేవలను అన్వేషించండి',
    savedSchemes: 'సేవ్ చేసిన పథకాలు',
    totalActivities: 'మొత్తం కార్యకలాపాలు',
    userCategory: 'వినియోగదారు వర్గం',
  },
  bn: {
    appName: 'Sarthi',
    tagline: 'জীবনের প্রতিটি পদক্ষেপে আপনার AI গাইড',
    selectLanguage: 'আপনার ভাষা নির্বাচন করুন',
    continue: 'চালিয়ে যান',
    login: 'লগইন',
    signup: 'সাইন আপ',
    logout: 'লগআউট',
    dashboard: 'ড্যাশবোর্ড',
    profile: 'প্রোফাইল',
    welcome: 'স্বাগতম',
    studentSupport: 'ছাত্র সহায়তা',
    govSchemes: 'সরকারি প্রকল্প',
    careerGuidance: 'ক্যারিয়ার গাইডেন্স',
    aiAssistant: 'AI সহায়ক',
    chat: 'AI এর সাথে চ্যাট',
    email: 'ইমেইল',
    password: 'পাসওয়ার্ড',
    name: 'পুরো নাম',
    dontHaveAccount: 'অ্যাকাউন্ট নেই?',
    alreadyHaveAccount: 'ইতিমধ্যে অ্যাকাউন্ট আছে?',
    getStarted: 'শুরু করুন',
    features: 'বৈশিষ্ট্য',
    aboutUs: 'আমাদের সম্পর্কে',
    howItWorks: 'এটি কিভাবে কাজ করে',
    multilingualSupport: 'বহুভাষিক সমর্থন',
    lowBandwidth: 'কম ব্যান্ডউইথ',
    freeForAll: 'সকল ভারতীয়ের জন্য বিনামূল্যে',
    studyPlanner: 'AI স্টাডি প্ল্যানার',
    doubtSolving: 'সন্দেহ সমাধান',
    mentalWellness: 'মানসিক সুস্থতা',
    schemeChecker: 'যোগ্যতা পরীক্ষক',
    skillRecommendation: 'দক্ষতার সুপারিশ',
    resumeTips: 'রিজুমে টিপস',
    jobAwareness: 'চাকরির সচেতনতা',
    askQuestion: 'আপনার প্রশ্ন জিজ্ঞাসা করুন...',
    send: 'পাঠান',
    voiceInput: 'ভয়েস ইনপুট',
    loading: 'লোড হচ্ছে...',
    viewDetails: 'বিস্তারিত দেখুন',
    checkEligibility: 'যোগ্যতা পরীক্ষা করুন',
    apply: 'আবেদন করুন',
    progressTracking: 'অগ্রগতি ট্র্যাকিং',
    chatHistory: 'চ্যাট ইতিহাস',
    settings: 'সেটিংস',
    newChat: 'নতুন চ্যাট',
    searchChats: 'চ্যাট খুঁজুন...',
    navigate: 'নেভিগেট করুন',
    pinned: '📌 পিন করা',
    today: 'আজ',
    yesterday: 'গতকাল',
    older: 'পুরানো',
    folders: 'ফোল্ডার',
    noConversations: 'এখনও কোন কথোপকথন নেই',
    citizenDashboard: 'নাগরিক ড্যাশবোর্ড',
    recentActivity: 'সাম্প্রতিক কার্যকলাপ',
    studyPlanStatus: 'স্টাডি প্ল্যান স্ট্যাটাস',
    exploreServices: 'পরিষেবাগুলি অন্বেষণ করুন',
    savedSchemes: 'সংরক্ষিত প্রকল্প',
    totalActivities: 'মোট কার্যকলাপ',
    userCategory: 'ব্যবহারকারী বিভাগ',
  },
  mr: {
    appName: 'Sarthi',
    tagline: 'जीवनाच्या प्रत्येक पावलावर तुमचा AI मार्गदर्शक',
    selectLanguage: 'तुमची भाषा निवडा',
    continue: 'सुरू ठेवा',
    login: 'लॉगिन',
    signup: 'साइन अप',
    logout: 'लॉगआउट',
    dashboard: 'डॅशबोर्ड',
    profile: 'प्रोफाइल',
    welcome: 'स्वागत आहे',
    studentSupport: 'विद्यार्थी समर्थन',
    govSchemes: 'सरकारी योजना',
    careerGuidance: 'करिअर मार्गदर्शन',
    aiAssistant: 'AI सहाय्यक',
    chat: 'AI शी चॅट करा',
    email: 'ईमेल',
    password: 'पासवर्ड',
    name: 'पूर्ण नाव',
    dontHaveAccount: 'खाते नाही?',
    alreadyHaveAccount: 'आधीच खाते आहे?',
    getStarted: 'सुरुवात करा',
    features: 'वैशिष्ट्ये',
    aboutUs: 'आमच्याबद्दल',
    howItWorks: 'हे कसे कार्य करते',
    multilingualSupport: 'बहुभाषिक समर्थन',
    lowBandwidth: 'कमी बँडविड्थ',
    freeForAll: 'सर्व भारतीयांसाठी विनामूल्य',
    studyPlanner: 'AI अभ्यास नियोजक',
    doubtSolving: 'शंका निराकरण',
    mentalWellness: 'मानसिक आरोग्य',
    schemeChecker: 'योजना पात्रता तपासक',
    skillRecommendation: 'कौशल्य शिफारसी',
    resumeTips: 'रिझ्यूम टिप्स',
    jobAwareness: 'नोकरी जागरूकता',
    askQuestion: 'तुमचा प्रश्न विचारा...',
    send: 'पाठवा',
    voiceInput: 'व्हॉइस इनपुट',
    loading: 'लोड करत आहे...',
    viewDetails: 'तपशील पहा',
    checkEligibility: 'पात्रता तपासा',
    apply: 'अर्ज करा',
    progressTracking: 'प्रगती ट्रॅकिंग',
    chatHistory: 'चॅट इतिहास',
    settings: 'सेटिंग्ज',
    newChat: 'नवीन चॅट',
    searchChats: 'चॅट शोधा...',
    navigate: 'नेव्हिगेट करा',
    pinned: '📌 पिन केलेले',
    today: 'आज',
    yesterday: 'काल',
    older: 'जुने',
    folders: 'फोल्डर्स',
    noConversations: 'अद्याप कोणतेही संभाषण नाही',
    citizenDashboard: 'नागरिक डॅशबोर्ड',
    recentActivity: 'अलिकडील क्रियाकलाप',
    studyPlanStatus: 'अभ्यास योजना स्थिती',
    exploreServices: 'सेवा एक्सप्लोर करा',
    savedSchemes: 'जतन केलेल्या योजना',
    totalActivities: 'एकूण क्रियाकलाप',
    userCategory: 'वापरकर्ता श्रेणी',
  },
  gu: {
    appName: 'Sarthi',
    tagline: 'જીવનના દરેક પગલે તમારો AI માર્ગદર્શક',
    selectLanguage: 'તમારી ભાષા પસંદ કરો',
    continue: 'ચાલુ રાખો',
    login: 'લોગિન',
    signup: 'સાઇન અપ',
    logout: 'લોગઆઉટ',
    dashboard: 'ડેશબોર્ડ',
    profile: 'પ્રોફાઇલ',
    welcome: 'સ્વાગત છે',
    studentSupport: 'વિદ્યાર્થી સહાય',
    govSchemes: 'સરકારી યોજનાઓ',
    careerGuidance: 'કારકિર્દી માર્ગદર્શન',
    aiAssistant: 'AI સહાયક',
    chat: 'AI સાથે ચેટ કરો',
    email: 'ઇમેઇલ',
    password: 'પાસવર્ડ',
    name: 'પૂરું નામ',
    dontHaveAccount: 'ખાતું નથી?',
    alreadyHaveAccount: 'પહેલેથી જ ખાતું છે?',
    getStarted: 'શરૂ કરો',
    features: 'સુવિધાઓ',
    aboutUs: 'અમારા વિશે',
    howItWorks: 'આ કેવી રીતે કામ કરે છે',
    multilingualSupport: 'બહુભાષી સપોર્ટ',
    lowBandwidth: 'ઓછી બેન્ડવિડ્થ',
    freeForAll: 'બધા ભારતીયો માટે મફત',
    studyPlanner: 'AI અભ્યાસ આયોજક',
    doubtSolving: 'શંકા નિરાકરણ',
    mentalWellness: 'માનસિક સ્વાસ્થ્ય',
    schemeChecker: 'યોજના પાત્રતા તપાસનાર',
    skillRecommendation: 'કુશળતા ભલામણો',
    resumeTips: 'રિઝ્યુમે ટિપ્સ',
    jobAwareness: 'નોકરી જાગૃતિ',
    askQuestion: 'તમારો પ્રશ્ન પૂછો...',
    send: 'મોકલો',
    voiceInput: 'વૉઇસ ઇનપુટ',
    loading: 'લોડ થઈ રહ્યું છે...',
    viewDetails: 'વિગતો જુઓ',
    checkEligibility: 'પાત્રતા તપાસો',
    apply: 'અરજી કરો',
    progressTracking: 'પ્રગતિ ટ્રેકિંગ',
    chatHistory: 'ચેટ ઇતિહાસ',
    settings: 'સેટિંગ્સ',
    newChat: 'નવી ચેટ',
    searchChats: 'ચેટ શોધો...',
    navigate: 'નેવિગેટ કરો',
    pinned: '📌 પિન કરેલ',
    today: 'આજે',
    yesterday: 'ગઈકાલે',
    older: 'જૂના',
    folders: 'ફોલ્ડર્સ',
    noConversations: 'હજુ સુધી કોઈ વાતચીત નથી',
    citizenDashboard: 'નાગરિક ડેશબોર્ડ',
    recentActivity: 'તાજેતરની પ્રવૃત્તિ',
    studyPlanStatus: 'અભ્યાસ યોજના સ્થિતિ',
    exploreServices: 'સેવાઓ અન્વેષણ કરો',
    savedSchemes: 'સાચવેલ યોજનાઓ',
    totalActivities: 'કુલ પ્રવૃત્તિઓ',
    userCategory: 'વપરાશકર્તા શ્રેણી',
  },
  kn: {
    appName: 'Sarthi',
    tagline: 'ಜೀವನದ ಪ್ರತಿ ಹೆಜ್ಜೆಯಲ್ಲೂ ನಿಮ್ಮ AI ಮಾರ್ಗದರ್ಶಿ',
    selectLanguage: 'ನಿಮ್ಮ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆ ಮಾಡಿ',
    continue: 'ಮುಂದುವರಿಸಿ',
    login: 'ಲಾಗಿನ್',
    signup: 'ಸೈನ್ ಅಪ್',
    logout: 'ಲಾಗ್ಔಟ್',
    dashboard: 'ಡ್ಯಾಶ್ಬೋರ್ಡ್',
    profile: 'ಪ್ರೊಫೈಲ್',
    welcome: 'ಸ್ವಾಗತ',
    studentSupport: 'ವಿದ್ಯಾರ್ಥಿ ಬೆಂಬಲ',
    govSchemes: 'ಸರ್ಕಾರಿ ಯೋಜನೆಗಳು',
    careerGuidance: 'ವೃತ್ತಿ ಮಾರ್ಗದರ್ಶನ',
    aiAssistant: 'AI ಸಹಾಯಕ',
    chat: 'AI ಜೊತೆ ಚಾಟ್ ಮಾಡಿ',
    email: 'ಇಮೇಲ್',
    password: 'ಪಾಸ್ವರ್ಡ್',
    name: 'ಪೂರ್ಣ ಹೆಸರು',
    dontHaveAccount: 'ಖಾತೆ ಇಲ್ಲವೇ?',
    alreadyHaveAccount: 'ಈಗಾಗಲೇ ಖಾತೆ ಇದೆಯೇ?',
    getStarted: 'ಪ್ರಾರಂಭಿಸಿ',
    features: 'ವೈಶಿಷ್ಟ್ಯಗಳು',
    aboutUs: 'ನಮ್ಮ ಬಗ್ಗೆ',
    howItWorks: 'ಇದು ಹೇಗೆ ಕೆಲಸ ಮಾಡುತ್ತದೆ',
    multilingualSupport: 'ಬಹುಭಾಷಾ ಬೆಂಬಲ',
    lowBandwidth: 'ಕಡಿಮೆ ಬ್ಯಾಂಡ್‌ವಿಡ್ತ್',
    freeForAll: 'ಎಲ್ಲಾ ಭಾರತೀಯರಿಗೆ ಉಚಿತ',
    studyPlanner: 'AI ಅಧ್ಯಯನ ಯೋಜಕ',
    doubtSolving: 'ಸಂದೇಹ ಪರಿಹಾರ',
    mentalWellness: 'ಮಾನಸಿಕ ಆರೋಗ್ಯ',
    schemeChecker: 'ಯೋಜನೆ ಅರ್ಹತೆ ಪರಿಶೀಲಕ',
    skillRecommendation: 'ಕೌಶಲ್ಯ ಶಿಫಾರಸುಗಳು',
    resumeTips: 'ರೆಸ್ಯೂಮ್ ಸಲಹೆಗಳು',
    jobAwareness: 'ಉದ್ಯೋಗ ಅರಿವು',
    askQuestion: 'ನಿಮ್ಮ ಪ್ರಶ್ನೆಯನ್ನು ಕೇಳಿ...',
    send: 'ಕಳುಹಿಸಿ',
    voiceInput: 'ಧ್ವನಿ ಇನ್‌ಪುಟ್',
    loading: 'ಲೋಡ್ ಆಗುತ್ತಿದೆ...',
    viewDetails: 'ವಿವರಗಳನ್ನು ವೀಕ್ಷಿಸಿ',
    checkEligibility: 'ಅರ್ಹತೆಯನ್ನು ಪರಿಶೀಲಿಸಿ',
    apply: 'ಅರ್ಜಿ ಸಲ್ಲಿಸಿ',
    progressTracking: 'ಪ್ರಗತಿ ಟ್ರ್ಯಾಕಿಂಗ್',
    chatHistory: 'ಚಾಟ್ ಇತಿಹಾಸ',
    settings: 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    newChat: 'ಹೊಸ ಚಾಟ್',
    searchChats: 'ಚಾಟ್‌ಗಳನ್ನು ಹುಡುಕಿ...',
    navigate: 'ನ್ಯಾವಿಗೇಟ್ ಮಾಡಿ',
    pinned: '📌 ಪಿನ್ ಮಾಡಲಾಗಿದೆ',
    today: 'ಇಂದು',
    yesterday: 'ನಿನ್ನೆ',
    older: 'ಹಳೆಯದು',
    folders: 'ಫೋಲ್ಡರ್‌ಗಳು',
    noConversations: 'ಇನ್ನೂ ಯಾವುದೇ ಚಾಟ್‌ಗಳಿಲ್ಲ',
    citizenDashboard: 'ನಾಗರಿಕ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    recentActivity: 'ಇತ್ತೀಚಿನ ಚಟುವಟಿಕೆ',
    studyPlanStatus: 'ಅಧ್ಯಯನ ಯೋಜನೆ ಸ್ಥಿತಿ',
    exploreServices: 'ಸೇವೆಗಳನ್ನು ಅನ್ವೇಷಿಸಿ',
    savedSchemes: 'ಉಳಿಸಿದ ಯೋಜನೆಗಳು',
    totalActivities: 'ಒಟ್ಟು ಚಟುವಟಿಕೆಗಳು',
    userCategory: 'ಬಳಕೆದಾರರ ವರ್ಗ',
  },
};

// Language code → BCP-47 locale tag for html lang attribute
const LANG_LOCALE: Record<Language, string> = {
  en: 'en', hi: 'hi', ta: 'ta', te: 'te', bn: 'bn', mr: 'mr', gu: 'gu', kn: 'kn'
};

function applyLanguageToDocument(lang: Language) {
  // Set lang attribute on <html> so browser, screen readers, and spellcheck use it
  document.documentElement.lang = LANG_LOCALE[lang] || lang;
  // All supported Indian scripts are LTR
  document.documentElement.dir = 'ltr';
  // Save preference
  localStorage.setItem('sarathi_language', lang);
}

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('sarathi_language') as Language;
    const resolved = saved && translations[saved] ? saved : 'en';
    // Apply immediately on load (before first render)
    applyLanguageToDocument(resolved);
    return resolved;
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    applyLanguageToDocument(lang);
  };

  const t = (key: string): string => {
    return translations[language]?.[key] || translations['en']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};
